<?php

?>

<div class="other_works">
            <h1>Other Works</h1>
            <p>Here is a sneak peek at David's most recent inspirational short story.</p>
            <h2>An Innkeeper's Journal: Excerpts Translated by Thomas Hennery</h2>
            <p>The discovery of the Paphos Scrolls, as they have come to be called, was a great event in historical academia. The results of the translation process provided an invaluable insight into the daily activities of the merchant class at the end of the meridian of time. Great care was given to safekeeping and eventual translation of these scrolls. Academics the world over came to lend wisdom as to the scrolls’ origin, significance and meaning. I was given the immense honor of leading the translation.</p>
            <p>​As the translation began, we soon became perplexed by the motivations of an ancient people who had obviously taken such care to preserve such a record. It was clear during our initial inquiries into the document’s authenticity, that this was not the original state of the manuscript. All agreed that this text had been copied from an original and laboriously recorded into a more enduring form. Reproduction may have happened multiple times before producing the copy in our possession. This implies that the ancients held this document in high esteem, high enough to imprint upon them a desire to protect its message for future generations.</p>
            <p>​With this bias in mind, we were puzzled and yet amazed that the document so far revealed only daily transactions and ledgers belonging to a relatively minor business enterprise. As for ourselves, a people long removed from understanding the daily activities of an ancient people’s forgotten habits, we found these details invaluable. It occurred to us that people located in time with these descriptions would have found them as moving as a modern man’s inspection of his local tannery’s inventory lists. This perplexity would last only so long.</p>
            <p>I imagine our Innkeeper, as we will only know him, was not much different from you or from me. As an inheritor of his location and vocation he had striven since his apprenticeship to maintain the tradition of his forbearers. He speaks sparingly of his own family, which at the time of the taxation consists of a wife, three daughters and two sons-in-law. We do hear of the youngest being a small child underfoot.</p>
            <p>While we must remember the thousands of years that separate us from him, remarkable similarities remain in the actions of one man then and any man now.  My own attempts to record my daily dealings often feel languid, utterly lacking in the kind of prose that would encourage one to read on. My days remain largely unremarkable. Ultimately, in each attempt, I abandon my efforts after only a short time. In fact many entries of my own journalings begin with an apology for the time lost since my last entry. Thus to document my thoughts and interactions remains a chore</p>
            <p>These same attitudes and feelings are strewn across the pages of our innkeeper’s manuscript. While he does relate the moments of celebration in his life (the births, the weddings) and the moments of heartbreak (the losses, the deaths) he mainly gives an account of occupancy and monetary figures relating to the inn and the occasional travelings of family and friends. Even in the cases of more substantial events, he retells them in the most basic of terms.</p>
            <p>Twenty-two days into our translation we found the author’s mannerisms starkly changed. The Innkeeper may have been approaching his fortieth year when the supreme lord of the realm Augustus, Emperor of Rome and heir of the great Julius, decreed the taxing of all his kingdom. An appreciation of this pronouncement would be imperative to the preparations of any enterprise, and none more apropos than the profession of an innkeeper. To obey this decree one must not only return a portion of wealth to the empire, but also each must physically return to the place of their family’s historical home to be counted. Augustus’s taxation was also a census, a reckoning of all subjects bound to the crown. Thus it required a migration of peoples in and across states and localities. Who better to benefit from such a proclamation than an innkeeper?</p>
            <p>The possibilities of this event were not lost on our Innkeeper. In his journal we read of a determined focus regarding the preparation of the inn at this time. His entries prior to this period, while meticulous in detail, give us little about the man engaged in their production. Where before an impersonal, even mundane description of the day’s events was characteristic, we now found the reason why this record was preserved by that people at that time, and why it’s witness must be revealed to our people in our time.</p>
            <p>​It is this change in style that punctuates the following entries so dramatically that they send chills down my spine and my heart racing even now as I recall their message. It is not to say that prior to this moment the entries were unworthy of examination, but this change has changed me. I write to impress upon the reader the idea that this man, who up until now rehearsed his daily life upon the pages of his text, now begins to pour his soul out to us and out to eternity.</p>
            <p>-Sir Thomas Hennery, 12th March 1888</p>
</div>